name = "OliveCollaborate"
uuid = "197e6993-98e3-4984-a077-c769f1bc4b7b"
authors = ["emmaccode <emmaccode@gmail.com>"]
version = "0.1.0"

[deps]
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"

[compat]
julia = "1.8"
Olive = "0.2.5"
